### ISSUE TITLE
Unused conflicted code?

### ISSUE THREAD

**Issue by gary5** [ngokevin/aframe-physics-components#6]
Hi,

I use this module with 'https://aframe.io/releases/latest/aframe.js' and find an issue.

_utils_ is undefined in AFRAME:
var coordinates = AFRAME.utils.coordinates;

I find it in _aframeCore_:
AFRAME.aframeCore.utils.coordinates

One more this is the variable _coordinates_ seems unused right now.

**Comment by ngokevin** [comment]
Hey thanks for filing. This component currently needs the dev branch of aframe, or the upcoming 0.2.0 release. There may or may not a regression in this component, need to look at it again
